### PR TITLE
resolves #48 add support for multifield-nested images

### LINKED ISSUE #48: Support multifield-nested image fields in generated dialogs
### Expected Behaviour

For the most part, an image field included in a composite multifield should support the same drag-drop behavior as an image field that is not included in a multifield.

### Actual Behaviour

Currently, the generated image field supports file upload, but not drag-drop, and the component fails to render the uploaded image after submitting the dialog.

#### Sample Code that illustrates the problem

For a standalone image field:

```json
            {
                "field": "imageTest",
                "type": "image",
                "label": "Image Test",
                "json-expose": true
            },
```

the following dialog xml is generated:

```xml
<imageTest 
    fieldLabel="Image Test"
    jcr:primaryType="nt:unstructured"        
    sling:resourceType="cq/gui/components/authoring/dialog/fileupload"                                             
    name="./imageTest/file"
    allowUpload="{Boolean}false"
    autoStart="{Boolean}false"
    class="cq-droptarget"
    fileReferenceParameter="./imageTest/fileReference"
    mimeTypes="[image/gif,image/jpeg,image/png,image/webp,image/tiff,image/svg+xml]"
    multiple="{Boolean}false"
    title="Drag to select image"
    uploadUrl="${suffix.path}"
    useHTML5="{Boolean}true"                                          
/>
<imageTestResType
    jcr:primaryType="nt:unstructured"
    sling:resourceType="granite/ui/components/coral/foundation/form/hidden"                                                     
    name="./imageTest/sling:resourceType"
    value="core/wcm/components/image/v2/image"
/>
```

For the same property config json nested in the items of a multifield, the following dialog xml is generated:

```xml
<imageTest 
    fieldLabel="Image Test"
    jcr:primaryType="nt:unstructured"                                                     
    name="./imageTest"                                                 
    sling:resourceType="cq/gui/components/authoring/dialog/fileupload"/>
```

### PR DESCRIPTION
**Pull request by adamcin**
## Description

* Added droptarget attributes and image restype to image fields nested in multifields
* Changed current version in pom to 1.1-SNAPSHOT
* Added executions to integration test phases to actually run the jar against the sample data-config.json file during the build
* Fixed bugs arising from this added smoketest execution

## Related Issue

see #48 

## Motivation and Context

Multifield images should have full support, because developers expect it.

## How Has This Been Tested?

tested generation against expected markup
tested generated model binding in htl
tested drag-drop functionality in author

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java [hunk 1]
```diff
@@ -300,11 +313,10 @@ private static void addBasicProperties(Element propertyNode, Property property)
      * @param property The {@link Property} object contains attributes
      */
     private static void addImagePropertyValues(Element imageNode, Property property) {
-        imageNode.setAttribute(Constants.PROPERTY_NAME, "./" + property.getField() + "/file");
-        imageNode.setAttribute(Constants.PROPERTY_CQ_MSM_LOCKABLE, "./" + property.getField() + "/file");
         imageNode.setAttribute("allowUpload", "{Boolean}false");
         imageNode.setAttribute("autoStart", "{Boolean}false");
         imageNode.setAttribute("class", "cq-droptarget");
+        imageNode.setAttribute("fileNameParameter", "./" + property.getField() + "/fileName");
```
Comment (HitmanInWis) [inline src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:321]: When we initially created this we purposely omitted the ability for an author to upload a file directly to a component (as opposed to referencing an asset in the DAM).  This helps promote asset reuse, asset organization and asset renditioning by forcing assets to all be in the DAM.  If we add this in, we should at least have it driven by a toggle so that it's not automatic.

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java [hunk 2]
```diff
@@ -264,7 +265,19 @@ private static void processItems(Document document, Node itemsNode, Property pro
             }
 
             if (StringUtils.equalsIgnoreCase("multifield", property.getType())) {
-                optionNode.setAttribute(Constants.PROPERTY_NAME, "./" + item.getField());
+                getPrimaryFieldName(item).ifPresent(name -> {
+                    optionNode.setAttribute(Constants.PROPERTY_NAME, name);
```
Comment (HitmanInWis) [inline src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:273]: Is cq_msm_lockable not applicable to fields within a multifield?

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java [hunk 3]
```diff
@@ -163,25 +163,34 @@ private static Element createPropertyNode(Document document, Node currentNode, P
...
-                && !property.getType().equalsIgnoreCase(Constants.TYPE_HEADING)) {
-            propertyNode.setAttribute(Constants.PROPERTY_NAME, "./" + property.getField());
-            propertyNode.setAttribute(Constants.PROPERTY_CQ_MSM_LOCKABLE, "./" + property.getField());
+        getPrimaryFieldName(property).ifPresent(name -> {
+            propertyNode.setAttribute(Constants.PROPERTY_NAME, name);
+            propertyNode.setAttribute(Constants.PROPERTY_CQ_MSM_LOCKABLE, name);
+        });
+
+        if ("image".equalsIgnoreCase(property.getType())) {
+            Element hiddenImageNode = document.createElement(property.getField() + "ResType");
```
Comment (HitmanInWis) [inline src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java]: Should we consolidate these lines of code, since it seems they are copy/pasted into the multifield scenario?

File: pom.xml [hunk 4]
```diff
@@ -5,7 +5,7 @@
     <modelVersion>4.0.0</modelVersion>
     <groupId>adobe</groupId>
     <artifactId>component-generator</artifactId>
-    <version>1.0</version>
+    <version>1.1-SNAPSHOT</version>
```
Comment (HitmanInWis) [inline pom.xml:8]: Should we just go with 1.1?

**Review by HitmanInWis — CHANGES_REQUESTED** [review]

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java (hunk 1 above)
Comment (adamcin) [reply src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:321]: It's still got `allowUpload="{Boolean}false"` as the default, i.e., no upload allowed by default. I just added this `fileNameParameter` attribute to bring the list of defaults into line with the fields supported by latest image v2. In fact, the way image components were being generated under multifields before this change actually resulted in them ONLY allowing upload, because the default `allowUpload="{Boolean}false"` preference wasn't being included on them.

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java (hunk 2 above)
Comment (adamcin) [reply src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:273]: I'm not sure. I didn't want to make an opinionated change on that without knowing either way.

File: pom.xml (hunk 4 above)
Comment (adamcin) [reply pom.xml:8]: Best practice is to keep it on snapshot on a branch and switch to release version for tagged commits.

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java (hunk 3 above)
Comment (adamcin) [reply src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java]: consolidated.

File: pom.xml (hunk 4 above)
Comment (HitmanInWis) [reply pom.xml:8]: how much effort would it be to set up downloadable releases for this project?

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java (hunk 2 above)
Comment (HitmanInWis) [reply src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:273]: Ah I suppose it's at least no different than how it had been working.

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java (hunk 1 above)
Comment (HitmanInWis) [reply src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:321]: ah k sounds good, thanks!

File: pom.xml (hunk 4 above)
Comment (adamcin) [reply pom.xml:8]: Not a whole lot of effort. With the level of commit activity you could basically manage it manually.

Comment (adamcin) [reply pom.xml:8]: image

Get here by clicking the Code <> tab, then the small Tags link

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java [hunk 5]
```diff
@@ -264,7 +265,17 @@ private static void processItems(Document document, Node itemsNode, Property pro
             }
 
             if (StringUtils.equalsIgnoreCase("multifield", property.getType())) {
-                optionNode.setAttribute(Constants.PROPERTY_NAME, "./" + item.getField());
+                getPrimaryFieldName(item).ifPresent(name -> {
```
Comment (HitmanInWis) [inline src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:272]: The updated code is adding multifield images to the sling model and dialog correctly, but the generated HTML isn't quite right.

```
<p>Path: ${item.path} | Label: ${item.label} | Link Icon: ${item.linkIcon}</p>
```

`item.linkIcon` doesnt render on the page since it's an Image object.  Our standard default rendered HTML for an image looks like this: ``

**Review by HitmanInWis — CHANGES_REQUESTED** [review]

File: src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java (hunk 5 above)
Comment (adamcin) [reply src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:272]: Aha, didn't even notice that bit of html. Will fix

Comment (adamcin) [reply src/main/java/com/adobe/aem/compgenerator/utils/DialogUtils.java:272]: @HitmanInWis I've updated this to at least dump the value of Image.src as a string, since the inline multifield item is rendered as a single, pipe-delimited line.

**Review by HitmanInWis — APPROVED** [review]
